version: "3.1"
services:       
  mongodb:
    container_name: mongo-dev
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=blog
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - '27017:27017'
    volumes:
        - mongodata:/data/db
    command: mongod
    expose:
      - 27017
          
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
    ports:
      - '8081:8081'

  backend:
    build: 
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    depends_on:
      - mongodb
    ports: 
      - "8002:8002"
    volumes:
      - ./backend/src:/app/backend/src
    links:
      - mongodb

  frontend:
    build: 
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    ports: 
      - "8001:8001"
    volumes:
      - ./frontend/src:/app/frontend/src

volumes:
  mongodata: